DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
    id                    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT        NOT NULL REFERENCES users(id),
    status                VARCHAR(32)   NOT NULL,
    total_price           NUMERIC(10,2) NOT NULL CHECK (total_price >= 0),
    order_number          VARCHAR(23)   NOT NULL,
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    cancelled_at          TIMESTAMPTZ,
    cancelled_by          BIGINT REFERENCES users(id),
    updated_at            TIMESTAMPTZ,
    updated_by            BIGINT REFERENCES users(id),
    shipping_full_name    VARCHAR(100)  NOT NULL,
    shipping_email        VARCHAR(254)  NOT NULL,
    shipping_phone        VARCHAR(20)   NOT NULL,
    shipping_country      VARCHAR(100)  NOT NULL,
    shipping_city         VARCHAR(100)  NOT NULL,
    shipping_address_line VARCHAR(200)  NOT NULL,

    CONSTRAINT orders_order_number_unique       UNIQUE (order_number),
    CONSTRAINT orders_order_number_format       CHECK (order_number ~ '^ORD-\d{8}-[A-Z0-9]{10}$'),
    CONSTRAINT orders_status_not_blank          CHECK (length(trim(status)) >= 1),
    CONSTRAINT orders_shipping_full_name_check  CHECK (length(trim(shipping_full_name)) >= 2),
    CONSTRAINT orders_shipping_phone_format     CHECK (shipping_phone ~ '^05\d{8}$')
);

CREATE INDEX idx_orders_user_created_at ON orders (user_id, created_at DESC);
