-- product_name / product_image_url / size are snapshot columns frozen at
-- insert. Rows are immutable thereafter (no UPDATE or DELETE path).
DROP TABLE IF EXISTS order_items CASCADE;

CREATE TABLE order_items (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT        NOT NULL REFERENCES orders(id),
    product_id        BIGINT        NOT NULL REFERENCES products(id),
    product_version   INTEGER       NOT NULL CHECK (product_version >= 1),
    quantity          INTEGER       NOT NULL CHECK (quantity >= 1),
    price_per_unit    NUMERIC(10,2) NOT NULL CHECK (price_per_unit >= 0),
    product_name      VARCHAR(200)  NOT NULL,
    product_image_url VARCHAR(500),
    size              VARCHAR(20)   NOT NULL,

    CONSTRAINT order_items_product_name_not_blank CHECK (length(trim(product_name)) >= 1)
);

CREATE INDEX idx_order_items_order ON order_items (order_id);
