CREATE TABLE payments (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT        NOT NULL REFERENCES orders(id),
    status         VARCHAR(32)   NOT NULL,
    amount         NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
    currency       VARCHAR(3)    NOT NULL DEFAULT 'USD',
    provider       VARCHAR(32)   NOT NULL,
    transaction_id VARCHAR(100)  NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT payments_order_unique       UNIQUE (order_id),
    CONSTRAINT payments_status_not_blank   CHECK (length(trim(status))   >= 1),
    CONSTRAINT payments_provider_not_blank CHECK (length(trim(provider)) >= 1),
    CONSTRAINT payments_currency_format    CHECK (currency ~ '^[A-Z]{3}$')
);
