DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE categories (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL,
    icon_filename  VARCHAR(100),
    updated_at     TIMESTAMPTZ,
    updated_by     BIGINT,
    is_deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMPTZ,
    deleted_by     BIGINT,
    CONSTRAINT categories_name_not_blank CHECK (length(trim(name)) >= 1)
);

CREATE INDEX idx_categories_active_name
    ON categories (name)
    WHERE is_deleted = FALSE;
