-- Users table per project-summary §1.1. Email stays UNIQUE forever (even after
-- soft-delete) so deactivated addresses cannot be re-registered. Phone is
-- constrained to the Israeli mobile shape used by the auth forms. Password
-- column is sized for any bcrypt $2*$ variant (current $2a$ produces 60 chars).
CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(50)  NOT NULL,
    last_name     VARCHAR(50)  NOT NULL,
    email         VARCHAR(254) NOT NULL UNIQUE,
    phone         VARCHAR(15)  NOT NULL,
    password_hash VARCHAR(72)  NOT NULL,
    is_admin      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMPTZ,
    deleted_by    BIGINT,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by    BIGINT,

    CONSTRAINT users_first_name_not_blank CHECK (length(trim(first_name)) >= 2),
    CONSTRAINT users_last_name_not_blank  CHECK (length(trim(last_name))  >= 2),
    CONSTRAINT users_phone_format         CHECK (phone ~ '^05\d{8}$'),
    CONSTRAINT users_deleted_by_fk        FOREIGN KEY (deleted_by) REFERENCES users(id),
    CONSTRAINT users_updated_by_fk        FOREIGN KEY (updated_by) REFERENCES users(id)
);

-- Login path filters WHERE email = ? AND is_deleted = FALSE; the partial
-- index keeps that hot lookup off the soft-deleted rows.
CREATE INDEX idx_users_active_email ON users (email) WHERE is_deleted = FALSE;
