DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(50)  NOT NULL,
    last_name     VARCHAR(50)  NOT NULL,
    -- stays unique even after soft-delete so deactivated addresses can't be reused
    email         VARCHAR(254) NOT NULL UNIQUE,
    phone         VARCHAR(15)  NOT NULL,
    -- fits any bcrypt $2*$ variant
    password_hash VARCHAR(72)  NOT NULL,
    is_admin      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMPTZ,
    deleted_by    BIGINT,
    updated_at    TIMESTAMPTZ,
    updated_by    BIGINT,

    CONSTRAINT users_first_name_not_blank CHECK (length(trim(first_name)) >= 2),
    CONSTRAINT users_last_name_not_blank  CHECK (length(trim(last_name))  >= 2),
    CONSTRAINT users_phone_format         CHECK (phone ~ '^05\d{8}$'),  -- Israeli mobile
    CONSTRAINT users_deleted_by_fk        FOREIGN KEY (deleted_by) REFERENCES users(id),
    CONSTRAINT users_updated_by_fk        FOREIGN KEY (updated_by) REFERENCES users(id)
);

-- partial: login lookup ignores soft-deleted rows
CREATE INDEX idx_users_active_email ON users (email) WHERE is_deleted = FALSE;
