-- Refresh tokens per project-summary §1.2 — single-session-per-user invariant
-- is enforced by UNIQUE(user_id) so /auth/login and /auth/refresh always
-- UPSERT into the same row instead of accumulating.
CREATE TABLE refresh_tokens (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    token        VARCHAR(255) NOT NULL,
    expires_at   TIMESTAMPTZ  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ,

    CONSTRAINT refresh_tokens_expires_after_created CHECK (expires_at > created_at)
);

-- Lookup indexes:
--   * user_id is already indexed by the UNIQUE(user_id) constraint above, so
--     "find this user's session" (/auth/logout, /auth/login UPSERT) is fast
--     without an explicit CREATE INDEX.
--   * token   -- /auth/refresh resolves the opaque cookie value to its row.
--   * expires_at -- the periodic cleanup job runs DELETE WHERE expires_at < NOW().
--   * last_used_at -- powers the future admin "active sessions" sort
--     (ORDER BY last_used_at DESC NULLS LAST).
CREATE INDEX idx_refresh_tokens_token        ON refresh_tokens (token);
CREATE INDEX idx_refresh_tokens_expires_at   ON refresh_tokens (expires_at);
CREATE INDEX idx_refresh_tokens_last_used_at ON refresh_tokens (last_used_at);
