-- UNIQUE(user_id) enforces one session per user; /auth/login & /auth/refresh UPSERT the same row
CREATE TABLE refresh_tokens (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    token        VARCHAR(255) NOT NULL,
    expires_at   TIMESTAMPTZ  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ,

    CONSTRAINT refresh_tokens_expires_after_created CHECK (expires_at > created_at)
);

CREATE INDEX idx_refresh_tokens_token        ON refresh_tokens (token);
CREATE INDEX idx_refresh_tokens_expires_at   ON refresh_tokens (expires_at);
CREATE INDEX idx_refresh_tokens_last_used_at ON refresh_tokens (last_used_at);
