DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE products (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200)  NOT NULL,
    description     TEXT,
    category_id     BIGINT        NOT NULL REFERENCES categories(id),
    is_multi_size   BOOLEAN       NOT NULL DEFAULT FALSE,
    image_filename  VARCHAR(200),
    price           NUMERIC(10,2) NOT NULL CHECK (price >= 0),
    version         INTEGER       NOT NULL DEFAULT 1,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,
    is_archived     BOOLEAN       NOT NULL DEFAULT FALSE,
    archived_at     TIMESTAMPTZ,
    archived_by     BIGINT REFERENCES users(id),
    CONSTRAINT products_name_not_blank CHECK (length(trim(name)) >= 1)
);

CREATE INDEX idx_products_active_name
    ON products (name)
    WHERE is_archived = FALSE;

CREATE INDEX idx_products_active_category
    ON products (category_id)
    WHERE is_archived = FALSE;
