INSERT INTO products (name, description, category_id, is_multi_size, image_filename, price)
SELECT v.name, v.description, c.id, v.is_multi_size, v.image_filename, v.price
FROM (VALUES
    -- Basketball
    ('Spalding NBA Basketball',
     'Official-size indoor/outdoor basketball with composite leather grip.',
     'Basketball', FALSE, 'basketball-spalding.jpg', 29.99),
    ('Spalding Street Basketball -- Black Edition',
     'Durable rubber street basketball, all-surface tested, matte black finish.',
     'Basketball', FALSE, 'basketball-spalding-black.jpg', 34.99),
    ('Rainbow Multi-Color Basketball',
     'Vibrant 8-panel rubber basketball. Great grip for outdoor play and skill drills.',
     'Basketball', FALSE, 'basketball-ball-multi-color.jpg', 24.99),
    ('Maccabi Tel Aviv Souvenir Basketball',
     'Yellow-and-blue souvenir basketball featuring the Maccabi Tel Aviv crest.',
     'Basketball', FALSE, 'basketball-ball-maccabi-tlv.jpg', 34.99),
    ('Nike Ja 3 Basketball Shoes',
     'Signature Ja Morant low-top with responsive Cushlon foam and a grippy herringbone outsole.',
     'Basketball', TRUE, 'nike-ja-3-shoes-basketball.jpg', 139.99),
    ('Nike LeBron Witness 8',
     'LeBron-line everyday performance basketball shoe with a Max Air heel unit.',
     'Basketball', TRUE, 'NIKE-LeBron-Witness-8-basketball-shoes-FB2239-005-Black-University-Red-White-1.jpg', 109.99),

    -- Soccer
    ('Nike Academy Soccer Ball',
     'Match-grade training ball with reinforced TPU casing and butyl bladder.',
     'Soccer', FALSE, 'soccer-ball-nike.jpg', 39.99),
    ('UCL 2025/26 Official Match Ball',
     'UEFA Champions League 2025/26 season official thermally-bonded match ball.',
     'Soccer', FALSE, 'soccer-ball-ucl-26.jpg', 149.99),
    ('Classic Red Match Soccer Ball',
     'All-red 32-panel match ball with a butyl bladder and machine-stitched seams.',
     'Soccer', FALSE, 'soccer-ball-red.jpg', 29.99),
    ('Manchester United Club Ball',
     'Manchester United-branded training ball, regulation size 5, with the club crest front and back.',
     'Soccer', FALSE, 'soccer-ball-manchester-united.jpg', 39.99),
    ('Spain National Team Supporters Ball',
     'Spain flag-styled supporters ball, regulation size 5, soft-touch surface.',
     'Soccer', FALSE, 'soccer-ball-spain.png', 34.99),
    ('adidas Tango River Plate Ball',
     'Retro reissue of the iconic Tango pentagon design from the 1978 World Cup era.',
     'Soccer', FALSE, 'soccer-ball-tango.jpg', 49.99),
    ('Nike Mercurial Superfly 9 "Believe"',
     'Speed-tier FG cleat with a Vaporposite+ upper and an Air Zoom unit underfoot.',
     'Soccer', TRUE, 'nike-superfly-9-white-soccer-shoe.jpg', 249.99),
    ('adidas F50 Elite FG',
     'Lightweight Sprintframe sole plate built for explosive acceleration in open play.',
     'Soccer', TRUE, 'adidas-f50-soccer-shoe.jpg', 229.99),
    ('adidas Predator Elite FG',
     'Fold-over tongue Predator with FacetFrame rubber strike zones for swerve and control.',
     'Soccer', TRUE, 'adidas-predetor-shoe.jpg', 269.99),
    ('adidas Predator Accuracy.1 "Solar Energy"',
     'Solar-green Predator with HybridTouch upper and a zone-skin strike pad.',
     'Soccer', TRUE, 'adidas-predetor-shoe-green.jpg', 239.99),
    ('adidas Copa Mundial',
     'The iconic K-leather cleat, hand-made in Germany since 1979.',
     'Soccer', TRUE, 'adidas_copa_mundial_soccer_shoe.jpg', 159.99),

    -- Volleyball
    ('Mikasa V200W Official Match Volleyball',
     'FIVB-approved official match ball used at major international tournaments.',
     'Volleyball', FALSE, 'Mikasa-volleyball-ball.png', 89.99),
    ('Vermont Beach Volleyball',
     'Soft-touch beach volleyball with a weather-resistant synthetic cover.',
     'Volleyball', FALSE, 'vermont-volleyball-ball.jpg', 34.99),

    -- Tennis
    ('Pro Carbon Tennis Racket',
     'Carbon-frame intermediate racket with a hybrid string pattern for spin and control.',
     'Tennis', FALSE, 'tennis-racket-silver.jpg', 129.99),
    ('Lightweight Composite Tennis Racket',
     'Composite frame with an oversized head — ideal for improving recreational players.',
     'Tennis', FALSE, 'tennis-racket-white-black-green.jpg', 99.99),
    ('Dunlop CX 200 Tour',
     'Tour-spec control racket favoured by competitive baseliners and all-court players.',
     'Tennis', FALSE, 'dunlop-tennis-racket.jpg', 229.99),

    -- Padel
    ('Wilson Bela Pro Padel Racket',
     'Carbon-fibre teardrop padel racket with an EVA core for power and feel.',
     'Padel', FALSE, 'padel-racket-green-black.jpg', 199.99),
    ('Wilson Tour Padel Racket',
     'All-court padel racket with a rough surface that adds bite and spin on every strike.',
     'Padel', FALSE, 'padel-racket-red.jpg', 179.99),

    -- Ping Pong
    ('Retractable Table Tennis Net',
     'Clip-on retractable net fitting tables up to 180cm wide. Tension-adjustable.',
     'Ping Pong', FALSE, 'ping-pong-net.jpg', 19.99),
    ('Beginner Table Tennis Racket',
     'Inverted-rubber racket ideal for casual play and first-time players.',
     'Ping Pong', FALSE, 'ping-pog-racket-begginer.jpg', 24.99),
    ('King Feel Carbon Pro Racket',
     '7-ply wood blade with 2 carbon layers and ITTF-approved rubber. Tournament-ready.',
     'Ping Pong', FALSE, 'ping-pong-racket-advanced.jpg', 79.99)
) AS v(name, description, category_name, is_multi_size, image_filename, price)
JOIN categories c ON c.name = v.category_name;
